# Generated by Django 4.0.5 on 2022-06-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_firm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='auth',
            field=models.CharField(blank=True, choices=[['s', 'Sotuvchi'], ['h', 'Haridor']], max_length=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/user_images/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
