# Generated by Django 4.0.5 on 2022-06-05 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_auth_alter_customuser_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='auth',
            field=models.CharField(blank=True, choices=[['s', 'Sotuvchi'], ['h', 'Haridor']], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='firm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.firm'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/user_images/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='firm',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='firm',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/firm_images/'),
        ),
        migrations.AlterField(
            model_name='firm',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='firm',
            name='tuman',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='firm',
            name='viloyat',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
