# Generated by Django 4.0.5 on 2022-06-05 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='media/product_image/')),
                ('viloyat', models.CharField(max_length=150)),
                ('tuman', models.CharField(max_length=150)),
                ('cost', models.IntegerField()),
                ('coifsenti', models.IntegerField()),
                ('about', models.TextField()),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.firm')),
            ],
        ),
        migrations.CreateModel(
            name='BuyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
